import React from 'react';
const arLang = {
  Home: 'الصفحة الرئيسية',
  Cart: 'عربة التسوق',
  Shop: 'متجر',
  News: 'أخبار',
  Search: 'بحث',
  Settings: 'إعدادات',
  GeneralSetting: 'الإعداد العام',
  MyWishlist: 'قائمة امنياتي',
  GetNotification: 'الحصول على إشعار',
  Language: 'لغة',
  MyOrders: 'طلباتي',
  Address: 'عنوان',
  AddAddress: 'اضف عنوان',
  EditAddress: 'تعديل العنوان',
  Currency: 'عملة',
  DarkTheme: 'مظهر داكن',
  LightTheme: 'مظهر خفيف',
  ContactUs: 'اتصل بنا',
  PrivacyPolice: 'سياسات الخصوصية',
  TermAndCondition: 'الشروط و الأحكام',
  AboutUs: 'معلومات عنا',
  RateTheApp: 'قيم التطبيق',
  IntroScreen: 'شاشة مقدمة',
  Profile: 'تحديث الملف',
  LogOut: 'تسجيل خروج',
  ChangeAppearance: 'تغيير المظهر',
  English: 'الإنجليزية',
  Arabic: 'عربى',
  Dark: 'داكن',
  Light: 'ضوء',
  SelectLanguage: 'اختار اللغة',
  SelectCurrency: 'اختر العملة',
  Login: 'تسجيل الدخول',
  Save: 'حفظ',
  Name: 'اسم',
  FullName: 'الاسم الكامل',
  YourComment: 'تعليقك',
  Email: 'البريد الإلكتروني',
  PhoneNo: 'رقم الهاتف',
  GlobalText:
    'الأمر كله يتعلق بالحد الأدنى من التمرين ، وممارسة التمارين الرياضية.الأمر كله يتعلق بالحد الأدنى من التمرين ، وممارسة التمارين الرياضية.الأمر كله يتعلق بالحد الأدنى من باستثناء حالات معينة ، يجب أن يكون الشخص مسؤولاً عن ممارسة الجنس، وممارسة التمارين الرياضية.باستثناء حالات معينة ، يجب أن يكون الشخص مسؤولاً عن ممارسة الج الأمر كله يتعلق بالحد الأدنى من التمرين ، وممارسة التمارين الرياضية.الأمر كله يتعلق بالحد الأدنى من التمرين ، وممارسة التمارين الرياضية.',
    GlobalText2: 'أمر كله يتعلق بالحد الأدنى من التمرين ، وممارسة التمارين الرياضية.الأمر كله يتعلق بالحد الأدنى من التمرين ، وممارسة التمارين الرياضية.',
  WebSiteTourist: 'موقع سياحي',
  APolicy: 'سياسة لزيادة الشفافية',
  WebsitePolicy: 'سياسة الموقع',
  FirstName: 'الاسم الاول',
  LastName: 'الكنية',
  City: 'مدينة',
  Pincode: 'الرمز السري',
  PhoneNumber: 'رقم الهاتف',
  Country: 'بلد',
  State: 'حالة',
  Select: 'تحديد',
  CustomizeTheme: 'تخصيص الموضوع',
  SelectyourSpecificColor: 'حدد اللون الخاص بك',
  SelectyourSpecificTheme: 'وضع الموضوع',
  ChanegFontSize: 'تغيير حجم الخط',
  ChangeFontFamily: 'تغيير عائلة الخط',
  SignIn: 'تسجيل الدخول',
  Username: 'اسم المستخدم',
  Password: 'كلمه السر',
  SignUp: 'سجل',
  DontHaveAnAccount: 'ليس لديك حساب؟',
  ForgotPassword: 'هل نسيت كلمة المرور؟',
  Or: 'أو',
  RememberMe: 'تذكرنى',
  InvalidEmail: 'بريد إلكتروني خاطئ',
  MinimumIsSix: 'الحد الأدنى المطلوب 6 أحرف',
  IwantToCreateAnAccount: 'اريد انشاء حساب',
  IAgreeWith: ' أنا أتفق مع',
  LoginToYourAccount: 'تسجيل الدخول إلى حسابك',
  CreatAnAccount: 'انشئ حساب',
  OnHold: 'في الانتظار',
  Processing: 'معالجة',
  Completed: 'منجز',
  Id: 'هوية شخصية',
  OrderDate: 'تاريخ الطلب',
  Status: 'الحالة',
  PaymentMethod: 'طريقة الدفع او السداد',
  Total: 'مجموع',
  Theme: 'موضوع',
  OrderDetail: 'تفاصيل الطلب',
  BillingAddress: 'عنوان وصول الفواتير',
  ShippingAddress: 'عنوان الشحن',
  Products: 'منتجات',
  Price: 'السعر',
  Quantity: 'كمية',
  Subtotal: 'المجموع الفرعي',
  ShippingMethod: 'طريقة الشحن',
  Totaltax: 'مجموع الضريبة',
  OrderNotes: 'ترتيب ملاحظات',
  Categories: 'التصنيفات',
  Category: 'الفئة',
  RecentSearches: 'عمليات البحث الأخيرة',
  Filter: 'منقي',
  Filters: 'المرشحات',
  ClearFilter: 'مرشح واضح',
  ProductsCategory: 'فئة المنتجات',
  ProductTags: 'علامات المنتج',
  Attributes: 'السمات',
  SortBy: 'ترتيب حسب',
  Recommended: 'موصى به',
  BestSelling: 'أفضل مبيعات',
  LowtoHigh: 'السعر من الارخص للاعلى',
  HightoLow: 'السعر الاعلى الى الادنى',
  Newest: 'الأحدث',
  Shirts: 'قمصان',
  Game: 'لعبة',
  Books: 'كتب',
  Gift: 'هدية',
  Bikes: 'دراجات',
  Cars: 'سيارات',
  Calculator: 'آلة حاسبة',
  Coffee: 'قهوة',
  More: 'أكثر',
  ViewMore: 'عرض المزيد',
  HotCategory: 'فئة ساخنة',
  FLashSale: 'بيع مفاجئ',
  MostLiked: 'الأكثر إعجابا',
  YouMayLike: 'قد يعجبك',
  DailyFeatured: 'المميزة اليومية',
  addToCart: 'أضف إلى السلة',
  ADDTOCART: 'أضف إلى السلة',
  ProductDetails: 'تفاصيل المنتج',
  EndsIn: 'ينتهي بـ',
  SelectColorSizeWeightQuantity: 'حدد اللون والحجم والوزن والكمية',
  BYCATEGORY: 'بالتصنيف',
  ProductDescription: 'وصف المنتج',
  CustomerReviews: 'آراء المستهلكين',
  Reviews: 'المراجعات',
  Wish: 'يتمنى',
  Orders: 'الطلب',
  rating: 'تقييم',
  Send: 'إرسال',
  YourMessage: 'رسالتك',
  GiveRating: 'منح التقييم',
  GiveReview: 'أعط مراجعة',
  BUYNOW: 'اشتري الآن',
  PromoCode: 'رمز ترويجي',
  EnterPromoCodeHere: 'أدخل الرمز الترويجي هنا',
  Apply: 'يتقدم',
  Discount: 'خصم',
  Tax: 'ضريبة',
  Shipping: 'شحن',
  SubTotal: 'المجموع الفرعي',
  Checkout: 'الدفع',
  WishList: 'قائمة الرغبات',
  PlaceOrder: 'مكان الامر',
  Next: 'التالي',
  SelectShippingMethod: 'إختر طريقة الشحن',
  MyProducts: 'منتجاتي',
  OrderNote: 'مذكرة النظام',
  WriteNote: 'اكتب ملا حظة',
  SelectPaymentMethod: 'اختار طريقة الدفع',
  ConfirmOrder: 'أكد الطلب',
  ThankYou: 'شكرا جزيلا',
  Yourorderwillbeshippedverysoon: 'سيتم شحن طلبك قريبًا جدًا',
  BackToHomePage: 'العودة إلى الصفحة الرئيسية',
  RemoveAll: 'حذف الكل',
  borderRadius: 'نصف قطر الحدود',
  BtnStyle: 'نمط الزر',
  homeStyle: 'حدد نمط المنزل',
  cardStyle: 'حدد نمط البطاقة',
  Searchforaproduct: 'البحث عن',
  Recomended: 'موصى به',
  MensCollections: 'مجموعات الرجال',
  Blog: 'مدونة او مذكرة',
  BlogDetails: 'تفاصيل المدونة',
  FreeShipping: 'الشحن مجانا',
  Localpickup: 'شاحنة محلية',
  ExpressShipping:'الشحن السريع',
  Stripe: 'شريط' ,
  Paypal: 'باي بال', 
  Razorpay: 'رازورباي', 
  Visa: 'تأشيرة دخول', 
  CashOnDelivery: 'الدفع عند الاستلام', 
  ECommerce: 'تجارة بابا',
  OnlineShopping: 'التسوق عبر الانترنت',
  ProductSearch: 'بحث منتوج',
  Notificatoins: 'اطلاعات',
  OnlineShoppingText: 'أكبر متجر للتسوق عبر الإنترنت في العالم يوفر آلاف المنتجات في مكان واحد',
  ProductSearchText: 'يسمح حقل البحث المباشر للعملاء بالعثور على المنتجات أثناء كتابتها ، جنبًا إلى جنب مع الصور ومعلومات الأسعار ويمكنهم إضافة المنتج مباشرة إلى سلة التسوق', 
  LiveFilters: 'مرشحات لايف',
  LiveFilterText: 'تهتم فلاترنا المباشرة بإظهار النتائج المحدثة على صفحة المتجر بينما يبحث عملاؤك عن طريق الكلمات الرئيسية أو النطاق السعري أو استخدام الفئات أو العلامات أو أي سمات منتج لتضييق نطاق النتائج',

  // Arabic translation

  // local data
  ShipmentveryfastGreatproductThankyou: 'الشحن سريع جدا منتج عظيم شكرا لكم',
  SelectedCosmicBlackOther: 'المحدد: هونج كونج + قميص + أخرى',
  '3874 Cedarstone Drive, Mansfield OH': '3874 سيدارستون درايف ، مانسفيلد أوهايو',
  '2084 Forest Drive,Chantilly,Virginia,22021': '2084 فورست درايف ، شانتيلي ، فيرجينيا ، 22021',
  '4122  Jennifer Lane,Durham,North Carolina,27703': '4122 جينيفر لين ، دورهام ، نورث كارولينا ، 27703',
  'Dr. Mark White' : 'دكتور مارك وايت',
  TShirt: 'تي شيرت',
  Mobile: 'التليفون المحمول',
  headphones: 'سماعات الرأس',
  Grocery: 'خضروات',
  Furniture: 'أثاث',
  Men: 'رجال',
  Baby: 'طفل',
  bed: 'سرير',
  Armchair: 'كرسي ذو ذراعين',
  Wingchair: 'كرسي الجناح',
  Woodchair: 'كرسي خشب',
  Foldingchair: 'كرسي ينطوي',
  Studentchair: 'كرسي الطالب',
  Sofa: 'كنبة',
  Salonchair: 'كرسي صالون',
  Deskchair: 'كرسي مكتب',
  Gardenchair: 'كرسي حديقة',
  Sony: 'سوني',
  JBL: 'اوديو تكنيكا',
  BangOlufsen: 'بانج & أمبير؛ أولفسن',
  Bose: 'بوس',
  BeatsbyDre: 'يدق بواسطة دري',
  Skullcandy: 'حلوى جمجمة',
  Beyerdynamic: 'باير ديناميكية',
  AKGAcoustics: 'الصوتيات',
  ArrowShirts: 'قمصان السهم',
  PeterEnglandShirts: 'قمصان بيتر انجلترا',
  VanHeusenShirts: 'قمصان فان هوسن',
  ZodiacShirts: 'قمصان زودياك',
  LouisPhillipeShirts: 'قمصان لويس فيليب',
  JohnPlayersShirts: 'قمصان جون بلايرز',
  ParkAvenueShirts: 'قمصان بارك أفينيو',
  ParxShirts: 'قمصان باركس',
  WillsLifestyleShirts: "قمصان ويلز لايف ستايل",
  AllenSollyShirts: 'قمصان ألين سولي',

  DressShirt: 'قميص اللباس',
  CubanCollarShirt: 'قميص الياقة الكوبي',
  Overshirt: 'قميص الياقة الكوبي',
  FlannelShirt: 'قميص خفيف',
  OfficeShirt: 'قميص المكتب',
  Chambray: 'شامبراي',
  ClassicShortSleeveShirt: 'قميص كلاسيكي بأكمام قصيرة',
  DenimShirt: 'قميص دينيم',
  LinenShirt: 'قميص كتان',
  OnSale:'للبيع',
  NewCollections: 'مجموعات جديدة',
  Apple: 'تفاحة',
  Mango: 'مانجو',
  Strawberry: 'الفراولة',
  Tomato: 'طماطم',
  Cauliflower: 'قرنبيط',
  Biscute: 'بسكويت',
  Lays: 'يضع',
  Chocklate: 'شوكولاتة',
  Upto: 'يصل إلى ',
  Off: '٪ عن',
  Weight: 'وزن',
  Size: 'بحجم',
  Colors: 'الألوان',
  Display: 'عرض',
  Processor: 'المعالج',
  Frequency: 'تكرر'
};

const engLang = {
  // local data
  Display: 'Display',
  Processor: 'Processor',
  Frequency: 'Frequency',
  Weight: 'Weight',
  Size: 'Size',
  Colors: 'Colors',
  Upto: 'Up to ',
  Off: '% Off',
  Chocklate: 'Chocklate',
  Lays: 'Lays',
  Biscute: 'Biscute',
  Cauliflower: 'Cauliflower',
  Tomato: 'Tomato',
  Strawberry: 'Strawberry',
  Mango: 'Mango',
  Apple: 'Apple',
  OnSale:'On Sale',
  MostLiked: 'Most Liked',
  NewCollections: 'New Collections',
  DressShirt: 'Dress Shirt',
  CubanCollarShirt: 'Cuban Collar Shirt',
  Overshirt: 'Overshirt',
  FlannelShirt: 'Flannel Shirt',
  OfficeShirt: 'Office Shirt',
  Chambray: 'Chambray',
  ClassicShortSleeveShirt: 'Classic Short Sleeve Shirt',
  DenimShirt: 'Denim Shirt',
  ArrowShirts: 'Arrow Shirts',
  LinenShirt: 'Linen Shirt',


  PeterEnglandShirts: 'Peter England Shirts',
  VanHeusenShirts: 'Van Heusen Shirts',
  ZodiacShirts: 'Zodiac Shirts',
  LouisPhillipeShirts: 'Louis Phillipe Shirts',
  JohnPlayersShirts: 'John Players Shirts',
  ParkAvenueShirts: 'Park Avenue Shirts',
  ParxShirts: 'Parx Shirts',
  WillsLifestyleShirts: "Wills Lifestyle Shirts",
  AllenSollyShirts: 'Allen Solly Shirts',

  Sony: 'Sony',
  JBL: 'Audio-Technica',
  BangOlufsen: 'Bang & Olufsen',
  Bose: 'Bose',
  BeatsbyDre: 'Beats by Dre',
  Skullcandy: 'Skullcandy',
  Beyerdynamic: 'Beyerdynamic',
  AKGAcoustics: 'AKG Acoustics',
  bed: 'Bed',
  Armchair: 'Armchair',
  Wingchair: 'Wing chair',
  Woodchair: 'Wood chair',
  Foldingchair: 'Folding chair',
  Studentchair: 'Student chair',
  Sofa: 'Sofa',
  Salonchair: 'Salon chair',
  Deskchair: 'Desk chair',
  Gardenchair: 'Garden chair',
  headphones: 'Headphones',
  Grocery: 'Grocery',
  Furniture: 'Furniture',
  Men: 'Men',
  Baby: 'baby',
  ShipmentveryfastGreatproductThankyou: 'Shipment very fast.Great product.Thank you',
  SelectedCosmicBlackOther: 'Selected:HK + Cosmic Black + other',
  '2084 Forest Drive,Chantilly,Virginia,22021': '2084 Forest Drive,Chantilly,Virginia,22021',
  '4122  Jennifer Lane,Durham,North Carolina,27703': '4122  Jennifer Lane,Durham,North Carolina,27703',
  'Dr. Mark White' : 'Dr. Mark White',
  '3874 Cedarstone Drive, Mansfield OH': '3874 Cedarstone Drive, Mansfield OH',
  TShirt: 'T Shirt',
  Mobile: 'Mobile',
  // labels
  LiveFilters: 'Live Filters',
  LiveFilterText: 'Our live filters take care of showing updated results on the shop page while your customers search by keyword, price range, use categories, tags or any product attributes to narrow down the results',
  ProductSearchText: 'The Live Search Field allows customers to find products as they type, along with images, price information and they can add the product directly to the cart',
  OnlineShoppingText: 'The Largest Store For Online Shopping In the world To Provide Thousands Of Products At One Stop',
  ECommerce: 'Baba Commerce',
  Notificatoins: 'Notificatoins',
  ProductSearch: 'Product Search',
  OnlineShopping: 'Online Shopping',
  Stripe: 'Stripe' ,
  Paypal: 'Paypal', 
  Razorpay: 'Razorpay', 
  Visa: 'Visa', 
  CashOnDelivery: 'Cash On Delivery',   
  FreeShipping: 'Free Shipping',
  Localpickup: 'Local pickup',
  ExpressShipping:'Express Shipping',
  BlogDetails: 'Blog Details',
  Blog: 'Blog',
  MensCollections: 'Mens Collections',
  Recomended: 'Recomended',
  Searchforaproduct: 'Search for',
  BtnStyle: 'Button Style',
  homeStyle: 'Select Home Style',
  cardStyle: 'Select Card Style',
  borderRadius: 'Border Radius',
  RemoveAll: 'Remove All',
  BackToHomePage: 'Back To Home Page',
  Yourorderwillbeshippedverysoon: 'Your order will be shipped very soon',
  ThankYou: 'Thank You',
  ConfirmOrder: 'Confirm Order',
  SelectPaymentMethod: 'Select Payment Method',
  WriteNote: 'Write Note',
  OrderNote: 'Order Note',
  MyProducts: 'My Products',
  SelectShippingMethod: 'Select Shipping Method',
  Next: 'Next',
  PlaceOrder: 'Place Order',
  WishList: 'WishList',
  Checkout: 'Checkout',
  Discount: 'Discount',
  Tax: 'Tax',
  Shipping: 'Shipping',
  SubTotal: 'SubTotal',
  Apply: 'Apply',
  EnterPromoCodeHere: 'Enter promo code here',
  PromoCode: 'Promo Code',
  GiveReview: 'Give Review',
  GiveRating: 'Give Rating',
  YourMessage: 'Your Message',
  Send: 'Send',
  rating: 'rating',
  Wish: 'Wish',
  Orders: 'Orders',
  Reviews: 'Reviews',
  CustomerReviews: 'Customer Reviews',
  BYCATEGORY: 'BY CATEGORY',
  ProductDescription: 'Product Description',
  SelectColorSizeWeightQuantity: 'Select Color, Size, Weight & Quantity',
  EndsIn: 'Ends in',
  addToCart: 'Add to Cart',
  ADDTOCART: 'ADD TO CART',
  BUYNOW: 'BUY NOW',
  ProductDetails: 'Product Detail',
  DailyFeatured: 'Daily Featured',
  FLashSale: 'Flash Sale',
  HotCategory: 'Hot Category',
  YouMayLike: 'You may like',
  More: 'More',
  ViewMore: 'View More',
  Shirts: 'Shirts',
  Game: 'Game',
  Books: 'Books',
  Gift: 'Gift',
  Bikes: 'Bikes',
  Cars: 'Cars',
  Calculator: 'Calculator',
  Coffee: 'Coffee',
  Recommended: 'Recommended',
  BestSelling: 'Best Selling',
  LowtoHigh: 'Price (Low to High)',
  HightoLow: 'Price (High to Low)',
  Newest: 'Newest',
  SortBy: 'Sort By',
  Attributes: 'Attributes',
  ProductTags: 'Product Tags',
  ProductsCategory: 'Products Category',
  Filter: 'Filter',
  ClearFilter: 'Clear Filter',
  Filters: 'Filters',
  RecentSearches: 'Recent Searches',
  Home: 'Home',
  Cart: 'Cart',
  Shop: 'Shop',
  Search: 'Search',
  Settings: 'Settings',
  GeneralSetting: 'General Setting',
  MyWishlist: 'My Wishlist',
  GetNotification: 'Get Notification',
  Language: 'Language',
  MyOrders: 'My Orders',
  Address: 'Address',
  AddAddress: 'Add Address',
  EditAddress: 'Edit Address',
  Currency: 'Currency',
  DarkTheme: 'Dark Theme',
  LightTheme: 'Light Theme',
  ContactUs: 'Contact Us',
  PrivacyPolice: 'Privacy Policies',
  TermAndCondition: 'Term & Condition',
  AboutUs: 'About Us',
  RateTheApp: 'Rate the App',
  IntroScreen: 'Intro Screen',
  Profile: 'Profile',
  LogOut: 'Log Out',
  ForgetPassword: 'Forget Password',
  ChangeAppearance: 'Change Appearance',
  English: 'English',
  Arabic: 'Arabic',
  Dark: 'Dark',
  Light: 'Light',
  SelectLanguage: 'Select Language',
  SelectCurrency: 'Select Currency',
  News: 'News',
  Login: 'Login',
  Save: 'Save',
  Name: 'Name',
  FullName: 'Full Name',
  YourComment: 'Your Comment',
  Email: 'Email',
  PhoneNo: 'Phone No',
  GlobalText:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    GlobalText2:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  WebSiteTourist: 'Website Tourist',
  APolicy: 'A Policy For Increased Transparency',
  WebsitePolicy: 'Website Privacy Policy',
  FirstName: 'First Name',
  LastName: 'Last Name',
  City: 'City',
  Pincode: 'Pincode',
  PhoneNumber: 'Phone Number',
  Country: 'Country',
  State: 'State',
  Select: 'Select',
  CustomizeTheme: 'Customize Theme',
  SelectyourSpecificColor: 'Select your Specific Color',
  SelectyourSpecificTheme: 'Theme Mode',
  ChanegFontSize: 'Change Font Size',
  ChangeFontFamily: 'Change Font Family',
  SignIn: 'Sign In',
  Username: 'User name',
  Or: 'OR',
  Password: 'Password',
  SignUp: 'Sign Up',
  DontHaveAnAccount: 'Dont have an account?',
  ForgotPassword: 'Forgot Password?',
  RememberMe: 'Remember me',
  InvalidEmail: 'invalid Email',
  MinimumIsSix: 'minimum 6 characters required',
  IwantToCreateAnAccount: 'I want to create an account',
  IAgreeWith: 'I agree with ',
  LoginToYourAccount: 'Login to your account',
  CreatAnAccount: 'Create an account',
  OnHold: 'On Hold',
  Processing: 'Processing',
  Completed: 'Completed',
  Id: 'Id',
  OrderDate: 'Order Date',
  Status: 'Status',
  PaymentMethod: 'Payment Method',
  Total: 'Total',
  Theme: 'Theme',
  OrderDetail: 'Order Detail',
  BillingAddress: 'Billing Address',
  ShippingAddress: 'Shipping Address',
  Products: 'Products',
  Price: 'Price',
  Quantity: 'Quantity',
  Subtotal: 'Subtotal',
  ShippingMethod: 'Shipping Method',
  Totaltax: 'Total tax',
  OrderNotes: 'Order Notes',
  Categories: 'Categories',
  Category: 'Category',

  // English translation
};

export { engLang, arLang };
